/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.DBConnection;
import ViewComponents.Dashboard;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author Hp
 */


public class SalesView extends javax.swing.JPanel {

    private Frame JPanel;

    /**
     * Creates new form Sales
     */
    public SalesView() {
        initComponents();
        getInvoiceNo();
        java.util.Date date = new java.util.Date();
        dateChooser.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void getInvoiceNo()
    {
        try{
        Connection con=DBConnection.createConnection();
        String query1= "SELECT MAX(sales_id) + 1 AS nextId FROM sales_product";
        PreparedStatement pstmt = con.prepareStatement(query1);

            // Execute the query
            ResultSet rs = pstmt.executeQuery();

            // Extract the next ID value
            if (rs.next()) {
                int nextId = rs.getInt("nextId");
                textInvoiceSales.setText(String.valueOf(nextId));
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Please Check again" ,"Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    public void sales(){
        String invId=textInvoiceSales.getText();
        String totalBillValue = textTotal.getText();
        String pay= textCashReceived.getText();
        String bal= textBalance.getText();
        java.util.Date date1= (java.util.Date) dateChooser.getDate();

        
        try {
            Connection con=DBConnection.createConnection();
            String query= "insert into sales(id, total_bill,cashreceived, balance,currentdate) values (?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);

            pst.setString(1, invId);
            pst.setString(2, totalBillValue);
            pst.setString(3, pay);
            pst.setString(4, bal);
            pst.setDate(5, new java.sql.Date(date1.getTime()));
            pst.executeUpdate();

           
            
            int rows= tableBilling.getRowCount();
            String query1= "insert into sales_product(sales_id, item_code, item_name, price, quantity, unit_total, currentdate) values (?,?,?,?,?,?,?)";
            PreparedStatement pst1=con.prepareStatement(query1);
            
            String invoiceId="";
            String itemcode="";
            String itemName="";
            String price="";
            String qty="";
            double total=0.0;
            java.util.Date date2;
            
            for(int i=0; i < tableBilling.getRowCount(); i++){
                invoiceId=(String)textInvoiceSales.getText();
                itemcode=(String)tableBilling.getValueAt(i, 0);
                itemName=(String)tableBilling.getValueAt(i, 1);
                price=(String)tableBilling.getValueAt(i, 2);
                qty=(String)tableBilling.getValueAt(i, 3);
                total=(double)tableBilling.getValueAt(i, 4);
                date2= (java.util.Date) dateChooser.getDate();
                
                pst1.setString(1,invoiceId);
                pst1.setString(2,itemcode);
                pst1.setString(3,itemName);
                pst1.setString(4,price);
                pst1.setString(5,qty);
                pst1.setDouble(6,total);
                pst1.setDate(7, new java.sql.Date(date2.getTime()));
                pst1.executeUpdate();
                
            }
           pst.addBatch();
           pst1.addBatch();
            JOptionPane.showMessageDialog(this, "Please wait. Bill is Printing");
            Map<String, Object> h1 = new HashMap<>();
            
            // Put the SQL parameter value into the map 
            h1.put("sales_id", invoiceId);
            JasperDesign jdesign=JRXmlLoader.load("C:\\Users\\Hp\\Documents\\Reports\\Invoice1.jrxml");
            JasperReport ireport= JasperCompileManager.compileReport(jdesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(ireport, h1, con);
            JasperViewer.viewReport(jasperPrint);      
            
        } 
        catch(SQLException e)
       {
           JOptionPane.showMessageDialog(this, "Database Error", "Error", JOptionPane.ERROR_MESSAGE);

       } catch (Exception e) {
          JOptionPane.showMessageDialog(this, "Please Check Again", "Error", JOptionPane.ERROR_MESSAGE);
   }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelSalesMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBilling = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textInvoiceSales = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textItemCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textItemName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textQuantity = new javax.swing.JTextField();
        buttonAddToBill = new javax.swing.JButton();
        textPrice = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        textCashReceived = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textBalance = new javax.swing.JTextField();
        buttonDelete = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textTotal = new javax.swing.JTextField();
        buttonaddSystem = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(675, 450));
        setMinimumSize(new java.awt.Dimension(675, 450));
        setPreferredSize(new java.awt.Dimension(675, 450));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(51, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sales - Demo");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setInheritsPopupMenu(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSalesMain.setBackground(new java.awt.Color(226, 253, 253));
        panelSalesMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelSalesMain.setPreferredSize(new java.awt.Dimension(675, 400));

        tableBilling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Price per Unit", "Qty", "Total"
            }
        ));
        tableBilling.setGridColor(new java.awt.Color(153, 255, 204));
        tableBilling.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jScrollPane1.setViewportView(tableBilling);

        jLabel9.setText("Sales Person");

        jTextField1.setBackground(new java.awt.Color(231, 231, 235));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Amashi");

        dateChooser.setBackground(new java.awt.Color(239, 237, 237));

        jLabel10.setText("Date");

        jLabel11.setText("Invoice No ");

        jPanel2.setBackground(new java.awt.Color(230, 250, 254));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Item Code");

        textItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textItemCodeActionPerformed(evt);
            }
        });
        textItemCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textItemCodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textItemCodeKeyReleased(evt);
            }
        });

        jLabel3.setText("Item Name");

        jLabel4.setText("Price");

        jLabel5.setText("Quantity");

        textQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textQuantityKeyPressed(evt);
            }
        });

        buttonAddToBill.setBackground(new java.awt.Color(153, 204, 255));
        buttonAddToBill.setText("Add To Bill");
        buttonAddToBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddToBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(textItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addComponent(textQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonAddToBill, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(textPrice))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textItemName)
                    .addComponent(textPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(textItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textQuantity)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(buttonAddToBill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));

        jLabel7.setText("Cash Received");

        textCashReceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCashReceivedActionPerformed(evt);
            }
        });
        textCashReceived.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textCashReceivedKeyReleased(evt);
            }
        });

        jLabel8.setText("Balance");

        buttonDelete.setBackground(new java.awt.Color(255, 153, 153));
        buttonDelete.setText("Delete item");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Sales Info");
        jLabel13.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(textBalance)
                            .addComponent(textCashReceived))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(32, 32, 32))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCashReceived, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(buttonDelete)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(223, 253, 253));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Grand Total");

        buttonaddSystem.setBackground(new java.awt.Color(153, 255, 153));
        buttonaddSystem.setText("Print Bill");
        buttonaddSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonaddSystemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(buttonaddSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textTotal)
                .addComponent(buttonaddSystem, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelSalesMainLayout = new javax.swing.GroupLayout(panelSalesMain);
        panelSalesMain.setLayout(panelSalesMainLayout);
        panelSalesMainLayout.setHorizontalGroup(
            panelSalesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalesMainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textInvoiceSales, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSalesMainLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelSalesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSalesMainLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelSalesMainLayout.setVerticalGroup(
            panelSalesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalesMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSalesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textInvoiceSales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSalesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSalesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSalesMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSalesMain, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    private void textItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textItemCodeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textItemCodeActionPerformed

    private void buttonaddSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonaddSystemActionPerformed

        sales();
//        try{
//            String sql="SELECT sales_product.sales_id,\n" +
//"	item_code,\n" +
//"	item_name,\n" +
//"	price,\n" +
//"	quantity,\n" +
//"	unit_total,\n" +
//"	total_bill,\n" +
//"	cashreceived,\n" +
//"	balance\n" +
//"FROM sales_product\n" +
//"	right join sales ON \n" +
//"	 sales_product.sales_id = sales.id \n" +
//"WHERE \n" +
//"	 sales_product.sales_id = $P{$_sales_id}\n" +
//"GROUP BY sales_product.sales_id";
//            Connection con = DBConnection.createConnection();
//            PreparedStatement pstmt = con.prepareStatement(sql);
//            String item=textInvoiceSales.getText();
//            pstmt.setString(1, item);
//            ResultSet rs = pstmt.executeQuery();
//
//            // Step 3: Pass the SQL parameter to Jasper Studio
//            // Load the Jasper report template
//            JasperCompileManager.compileReportToFile("C:\\Users\\Hp\\Documents\\Reports\\invoice1.jrxml");
//            Map<String, Object> parameters = new HashMap<>();
//            
//            // Put the SQL parameter value into the map using the parameter name defined in the report template
//            parameters.put("sales_id", item);
//
//            // Generate the report
//            JasperPrint jasperPrint = JasperFillManager.fillReport("C:\\Users\\Hp\\Documents\\Reports\\invoice1.jasper", parameters, con);
//            
//            // Display or export the generated report as needed
            // ...
            
//
//            // Create a map of parameters
//            String reportPath = "C:\\Users\\Hp\\Documents\\Reports\\invoice1.jrxml";
//            JasperReport jr = JasperCompileManager.compileReport(reportPath);
//            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
//            JasperViewer.viewReport(jp);
//            con.close();
//        }
//
//        }
//        catch(Exception ex)
//        {
//            ex.printStackTrace();
//        }
//           

    }//GEN-LAST:event_buttonaddSystemActionPerformed

    private void textItemCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textItemCodeKeyReleased
        // TODO add your handling code here:
       try
        {
          if(evt.getKeyCode()== KeyEvent.VK_ENTER)
          {
          String sql="select * from products where itemCode=?";
          Connection con=DBConnection.createConnection();
          
          String itemCode=textItemCode.getText();
          PreparedStatement statement1=con.prepareStatement(sql);
          statement1.setString(1, itemCode);
          ResultSet rs=statement1.executeQuery();
          
          if(rs.next()== true){
              String name=rs.getString("itemName");
              String price=rs.getString("itemPrice");
              textItemName.setText(name.trim());
              textPrice.setText(price.trim());
             
          }
          
          else{
              JOptionPane.showMessageDialog(this, "Item Code Not Found");
              textItemName.setText("");
              textPrice.setText("");
          }
          }
          
        }catch(SQLException e)
       {
           JOptionPane.showMessageDialog(this, "Database Error", "Error", JOptionPane.ERROR_MESSAGE);

       } catch (Exception e) {
          JOptionPane.showMessageDialog(this, "Please Check Again", "Error", JOptionPane.ERROR_MESSAGE);
   }

        
    }//GEN-LAST:event_textItemCodeKeyReleased

    private void buttonAddToBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddToBillActionPerformed
        // TODO add your handling code here:
        String itemCode=(textItemCode.getText());
        String name=(textItemName.getText());
        double price= Double.parseDouble(textPrice.getText());
        double quantity= Double.parseDouble(textQuantity.getText());
        double total=quantity*price;
 
        
        DefaultTableModel model = (DefaultTableModel) tableBilling.getModel();
        
        model.addRow(new Object[]
        {
            textItemCode.getText(),
            textItemName.getText(),
            textPrice.getText(),
            textQuantity.getText(),
            total,
        });
        
        double sum=0;
        for(int i=0; i<tableBilling.getRowCount(); i++){
            sum=sum+ Double.parseDouble(tableBilling.getValueAt(i, 4).toString());
        }
        
        
        textTotal.setText(String.valueOf(sum));
        
        textItemCode.setText("");
        textItemName.setText("");
        textPrice.setText("");
        textQuantity.setText("");
        textItemCode.requestFocus();
             
        
    }//GEN-LAST:event_buttonAddToBillActionPerformed

    private void textCashReceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCashReceivedActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textCashReceivedActionPerformed

    private void textCashReceivedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCashReceivedKeyReleased
        // TODO add your handling code here:
            double balance, total, cashReceived;
          
            if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
            total = Double.parseDouble(textTotal.getText());
            cashReceived = Double.parseDouble(textCashReceived.getText());
 
 
            balance = cashReceived - total;
            textBalance.setText(String.valueOf(balance));
            }
            
    }//GEN-LAST:event_textCashReceivedKeyReleased

    private void textItemCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textItemCodeKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textItemCodeKeyPressed

    private void textQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textQuantityKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantityKeyPressed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed

        DefaultTableModel model = (DefaultTableModel) tableBilling.getModel();
        model.removeRow(tableBilling.getSelectedRow());
        double sum=0;
        for(int i=0; i<tableBilling.getRowCount(); i++){
            sum=sum+ Double.parseDouble(tableBilling.getValueAt(i, 4).toString());
        }
         textTotal.setText(Double.toString(sum));
    }//GEN-LAST:event_buttonDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddToBill;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonaddSystem;
    private com.toedter.calendar.JDateChooser dateChooser;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelSalesMain;
    private javax.swing.JTable tableBilling;
    private javax.swing.JTextField textBalance;
    private javax.swing.JTextField textCashReceived;
    private javax.swing.JTextField textInvoiceSales;
    private javax.swing.JTextField textItemCode;
    private javax.swing.JTextField textItemName;
    private javax.swing.JTextField textPrice;
    private javax.swing.JTextField textQuantity;
    private javax.swing.JTextField textTotal;
    // End of variables declaration//GEN-END:variables


}
